name: Trigger auto deployment for ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ui-AutoDeployTrigger-f0a217c4-0f28-4d88-a041-1a0dca7b269a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bsdccr.azurecr.io
          username: ${{ secrets.UI_REGISTRY_USERNAME }}
          password: ${{ secrets.UI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bsdccr.azurecr.io/ui:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ui -g bsdProductionRG --server bsdccr.azurecr.io --username  ${{ secrets.UI_REGISTRY_USERNAME }} --password ${{ secrets.UI_REGISTRY_PASSWORD }}
            az containerapp update -n ui -g bsdProductionRG --image bsdccr.azurecr.io/ui:${{ github.sha }}
